apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
    environment: staging
spec:
  selector:
    matchLabels:
      component: backend
  namespaceSelector:
    matchNames:
      - ecommerce
  endpoints:
  - port: http
    targetPort: 8000
    path: /metrics
    interval: 15s

